# Generated by Django 4.2.4 on 2023-09-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0002_eletiva_student_student_eletiva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_eletiva",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
