# Generated by Django 4.2.4 on 2023-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0003_alter_student_student_eletiva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
