# Generated by Django 4.2.4 on 2023-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0005_remove_guest_email_guest_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="guest", name="phone",),
        migrations.AddField(
            model_name="guest",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
