# Generated by Django 4.2.4 on 2023-10-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0007_rename_eletiva_name_eletiva_eletiva_group_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="eletiva", name="eletiva_group_name",),
        migrations.RemoveField(model_name="student", name="student_eletiva",),
        migrations.AddField(
            model_name="eletiva",
            name="eletiva_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=50)),
                (
                    "eletiva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="guest.eletiva"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="eletiva_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="guest.group"
            ),
        ),
    ]
