# Generated by Django 4.2.4 on 2023-10-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0008_remove_eletiva_eletiva_group_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="eletiva",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guest.eletiva"
            ),
        ),
    ]
