# Generated by Django 4.2.4 on 2023-10-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0009_alter_group_eletiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="student_visited",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="guest.student",
            ),
            preserve_default=False,
        ),
    ]
