# Generated by Django 4.2.4 on 2023-10-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0011_remove_guest_student_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="student_visited",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guest.student",
            ),
        ),
    ]
