# Generated by Django 4.2.4 on 2023-10-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0012_guest_student_visited"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="visits",),
        migrations.AlterField(
            model_name="guest", name="email", field=models.EmailField(max_length=100),
        ),
    ]
