# Generated by Django 4.2.4 on 2023-10-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0013_remove_student_visits_alter_guest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="student_visited",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_visits",
                to="guest.student",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="verification_code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
