# Generated by Django 4.2.4 on 2024-10-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_guest_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='verification_code',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
