# Generated by Django 4.2.4 on 2024-10-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0017_rename_verification_code_guest_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='cpf',
            new_name='verification_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='codigo',
        ),
    ]
