# Generated by Django 4.2.4 on 2024-10-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0019_remove_student_eletiva_group_student_anosemestre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='anosemestre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='eletiva_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.group'),
        ),
    ]
