# Generated by Django 4.2.4 on 2024-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0021_rename_verification_code_guest_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
