# Generated by Django 4.2.4 on 2024-10-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0022_alter_student_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='eletiva',
        ),
        migrations.DeleteModel(
            name='Eletiva',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
